/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export function Model(props) {
    const { nodes, materials } = useGLTF("/bsb.glb");
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.burger_bottom.geometry}
                material={materials["Burger Bun"]}
                position={[0.078, 0.233, 0]}
                scale={[1.082, 0.958, 0.958]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.burger_top.geometry}
                    material={materials.coffee_with_milk}
                    position={[0.077, 0.063, 0]}
                    scale={[0.59, 0.667, 0.667]}
                >
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed001.geometry}
                        material={materials.seed}
                        position={[1.072, 0.763, -1.258]}
                        rotation={[1.775, 0.187, -0.869]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed002.geometry}
                        material={materials.seed}
                        position={[1.341, 0.55, -1.033]}
                        rotation={[1.462, 0.19, -0.651]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed003.geometry}
                        material={materials.seed}
                        position={[-0.13, 0.979, 1.322]}
                        rotation={[-1.907, -0.181, -1.572]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed004.geometry}
                        material={materials.seed}
                        rotation={[Math.PI, 0, -Math.PI / 2]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed005.geometry}
                        material={materials.seed}
                        position={[0.364, 1.72, -0.078]}
                        rotation={[-3.048, -0.018, -1.194]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed006.geometry}
                        material={materials.seed}
                        position={[0.519, 1.277, -1.263]}
                        rotation={[2.538, 0.11, -1.138]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed007.geometry}
                        material={materials.seed}
                        position={[1.279, 0.748, 0.633]}
                        rotation={[-2.4, -0.13, -0.789]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed008.geometry}
                        material={materials.seed}
                        position={[0.607, 0.95, 1.124]}
                        rotation={[-2.232, -0.152, -1.113]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed009.geometry}
                        material={materials.seed}
                        position={[-0.219, 1.336, 1.073]}
                        rotation={[-2.453, -0.122, -1.43]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed010.geometry}
                        material={materials.seed}
                        position={[-1, 1.796, -0.093]}
                        rotation={[-3.07, -0.014, -1.704]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed011.geometry}
                        material={materials.seed}
                        position={[-1.049, 1.792, -0.176]}
                        rotation={[-3.116, -0.005, -1.776]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed012.geometry}
                        material={materials.seed}
                        position={[-0.986, 1.804, -0.261]}
                        rotation={[3.133, 0.002, -1.706]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed013.geometry}
                        material={materials.seed}
                        position={[-0.96, 1.805, -0.33]}
                        rotation={[3.103, 0.007, -1.688]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed014.geometry}
                        material={materials.seed}
                        position={[0.163, 1.405, -1.31]}
                        rotation={[2.523, 0.112, -1.29]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed015.geometry}
                        material={materials.seed}
                        position={[0.272, 1.384, -1.277]}
                        rotation={[2.567, 0.105, -1.236]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed016.geometry}
                        material={materials.seed}
                        position={[0.538, 1.334, -1.145]}
                        rotation={[2.588, 0.102, -1.129]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed017.geometry}
                        material={materials.seed}
                        position={[0.669, 1.366, -0.945]}
                        rotation={[2.614, 0.097, -1.066]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed018.geometry}
                        material={materials.seed}
                        position={[0.809, 1.223, -1.038]}
                        rotation={[2.587, 0.102, -1.007]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed019.geometry}
                        material={materials.seed}
                        position={[0.951, 1.14, -0.989]}
                        rotation={[2.601, 0.099, -0.942]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed020.geometry}
                        material={materials.seed}
                        position={[0.843, 1.284, -0.873]}
                        rotation={[2.626, 0.095, -0.977]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed021.geometry}
                        material={materials.seed}
                        position={[0.996, 1.132, -0.932]}
                        rotation={[2.614, 0.097, -0.915]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed022.geometry}
                        material={materials.seed}
                        position={[1.451, 0.828, -0.083]}
                        rotation={[-2.98, -0.031, -0.663]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed023.geometry}
                        material={materials.seed}
                        position={[1.064, 1.033, 0.559]}
                        rotation={[-2.447, -0.123, -0.854]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed024.geometry}
                        material={materials.seed}
                        position={[0.859, 0.994, 0.862]}
                        rotation={[-2.353, -0.137, -0.988]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed025.geometry}
                        material={materials.seed}
                        position={[0.505, 1.111, 1.019]}
                        rotation={[-2.361, -0.136, -1.15]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed026.geometry}
                        material={materials.seed}
                        position={[0.383, 1.287, 0.891]}
                        rotation={[-2.407, -0.129, -1.209]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed027.geometry}
                        material={materials.seed}
                        position={[-0.679, 1.688, 0.512]}
                        rotation={[-2.765, -0.071, -1.621]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed028.geometry}
                        material={materials.seed}
                        position={[-0.839, 1.775, 0.183]}
                        rotation={[-2.937, -0.039, -1.671]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed029.geometry}
                        material={materials.seed}
                        position={[-0.647, 1.82, 0.033]}
                        rotation={[-3.01, -0.025, -1.655]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed030.geometry}
                        material={materials.seed}
                        position={[-0.823, 1.815, -0.095]}
                        rotation={[-3.074, -0.013, -1.675]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed031.geometry}
                        material={materials.seed}
                        position={[-0.763, 1.812, -0.457]}
                        rotation={[3.033, 0.021, -1.639]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed032.geometry}
                        material={materials.seed}
                        position={[-0.59, 1.835, -0.333]}
                        rotation={[3.072, 0.013, -1.628]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed033.geometry}
                        material={materials.seed}
                        position={[-0.706, 1.81, -0.505]}
                        rotation={[3.004, 0.027, -1.627]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed034.geometry}
                        material={materials.seed}
                        position={[-0.129, 1.609, -1.067]}
                        rotation={[2.706, 0.082, -1.395]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed035.geometry}
                        material={materials.seed}
                        position={[0.289, 1.532, -0.986]}
                        rotation={[2.65, 0.091, -1.244]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed036.geometry}
                        material={materials.seed}
                        position={[0.433, 1.559, -0.804]}
                        rotation={[2.697, 0.083, -1.182]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed037.geometry}
                        material={materials.seed}
                        position={[0.7, 1.422, -0.789]}
                        rotation={[2.671, 0.088, -1.043]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed038.geometry}
                        material={materials.seed}
                        position={[0.832, 1.438, -0.496]}
                        rotation={[2.835, 0.058, -0.948]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed039.geometry}
                        material={materials.seed}
                        position={[1.071, 1.247, -0.441]}
                        rotation={[2.88, 0.05, -0.813]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed040.geometry}
                        material={materials.seed}
                        position={[1.193, 1.149, -0.215]}
                        rotation={[3.113, 0.005, -0.736]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed041.geometry}
                        material={materials.seed}
                        position={[1.034, 1.294, 0.037]}
                        rotation={[-2.907, -0.045, -0.808]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed042.geometry}
                        material={materials.seed}
                        position={[1.173, 1.157, -0.011]}
                        rotation={[-2.939, -0.039, -0.74]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed043.geometry}
                        material={materials.seed}
                        position={[0.355, 1.4, 0.764]}
                        rotation={[-2.464, -0.121, -1.228]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed044.geometry}
                        material={materials.seed}
                        position={[-0.108, 1.746, 0.35]}
                        rotation={[-2.784, -0.068, -1.475]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed045.geometry}
                        material={materials.seed}
                        position={[-0.149, 1.784, -0.599]}
                        rotation={[2.883, 0.05, -1.466]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed046.geometry}
                        material={materials.seed}
                        position={[0.057, 1.694, -0.775]}
                        rotation={[2.767, 0.071, -1.363]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed047.geometry}
                        material={materials.seed}
                        position={[0.374, 1.649, -0.637]}
                        rotation={[2.788, 0.067, -1.217]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed048.geometry}
                        material={materials.seed}
                        position={[0.393, 1.59, 0.428]}
                        rotation={[-2.665, -0.089, -1.214]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed049.geometry}
                        material={materials.seed}
                        position={[0.318, 1.608, 0.452]}
                        rotation={[-2.656, -0.09, -1.255]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed050.geometry}
                        material={materials.seed}
                        position={[0.116, 1.785, 0.068]}
                        rotation={[-2.972, -0.033, -1.331]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed051.geometry}
                        material={materials.seed}
                        position={[-0.042, 1.817, 0.048]}
                        rotation={[-2.993, -0.029, -1.449]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed052.geometry}
                        material={materials.seed}
                        position={[-0.082, 1.829, -0.014]}
                        rotation={[-3.035, -0.021, -1.471]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed053.geometry}
                        material={materials.seed}
                        position={[0.155, 1.795, -0.175]}
                        rotation={[-3.127, -0.003, -1.317]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed054.geometry}
                        material={materials.seed}
                        position={[0.119, 1.793, -0.356]}
                        rotation={[3, 0.027, -1.359]}
                        scale={0.023}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.seaseme_seed055.geometry}
                        material={materials.seed}
                        position={[0.431, 1.665, -0.509]}
                        rotation={[2.864, 0.053, -1.187]}
                        scale={0.023}
                    />
                </mesh>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mic_body.geometry}
                    material={materials["Material.003"]}
                    position={[0.222, -0.101, -0.054]}
                    rotation={[0.324, 0.002, -1.769]}
                    scale={[0.499, 0.446, 0.501]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mic_head.geometry}
                    material={materials["Material.002"]}
                    position={[-0.545, 0.063, 0]}
                    rotation={[0.321, 0.004, -0.198]}
                    scale={[0.522, 0.584, 0.586]}
                />
            </mesh>
            <PerspectiveCamera
                makeDefault={false}
                far={100}
                near={0.1}
                fov={39.598}
                position={[0, 0, 5.311]}
            />
        </group>
    );
}

useGLTF.preload("/bsb.glb");
