/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/vampire.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene" position={[9.5,2,0]} rotation={[-1.8, -2.9, -3]}>
        <mesh
          name="Circle"
          castShadow
          receiveShadow
          geometry={nodes.Circle.geometry}
          material={materials.Material}
        />
        <group name="Empty" position={[0, -0.74, 0]} />
        <mesh
          name="Cube"
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials['Material.001']}
          position={[0, -0.904, 0]}
          scale={[1.066, 1.1, 1.066]}
        />
        <mesh
          name="Cube001"
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials['Material.002']}
          position={[0, -0.916, 0]}
          rotation={[0, -Math.PI / 4, 0]}
        />
        <mesh
          name="Circle001"
          castShadow
          receiveShadow
          geometry={nodes.Circle001.geometry}
          material={materials['Material.001']}
          position={[3.894, -0.739, 0]}
          scale={0.77}
        />
        <mesh
          name="Circle002"
          castShadow
          receiveShadow
          geometry={nodes.Circle002.geometry}
          material={materials['Material.001']}
          position={[0, -0.739, -3.796]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.866}
        />
        <mesh
          name="Cylinder"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={materials['Material.002']}
          position={[0, -0.74, 3.1]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Plane"
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials['Material.001']}
          position={[0, -0.74, 2.62]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Cylinder001"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials.Material}
          position={[0, -0.74, 10.049]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Cube005"
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={materials['Material.001']}
          position={[-0.576, -0.74, 10.049]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          name="Icosphere"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere.geometry}
          material={materials['Material.002']}
          position={[-6.709, -0.702, 7.593]}
          rotation={[0, 0, -2.182]}
          scale={1.799}
        />
        <mesh
          name="Torus001"
          castShadow
          receiveShadow
          geometry={nodes.Torus001.geometry}
          material={materials['Material.002']}
          position={[-0.486, -0.888, -6.214]}
          rotation={[-0.536, 0.731, 1.859]}
        />
        <mesh
          name="Torus002"
          castShadow
          receiveShadow
          geometry={nodes.Torus002.geometry}
          material={materials['Material.002']}
          position={[-1.341, -1.519, -6.74]}
          rotation={[-0.826, 0.599, 0.465]}
        />
        <mesh
          name="Torus003"
          castShadow
          receiveShadow
          geometry={nodes.Torus003.geometry}
          material={materials['Material.002']}
          position={[-2.294, -2.176, -6.961]}
          rotation={[-1.466, 1.041, -0.599]}
        />
        <mesh
          name="Torus004"
          castShadow
          receiveShadow
          geometry={nodes.Torus004.geometry}
          material={materials['Material.002']}
          position={[-3.313, -2.802, -6.858]}
          rotation={[-1.676, 0.973, -1.997]}
        />
        <mesh
          name="Torus005"
          castShadow
          receiveShadow
          geometry={nodes.Torus005.geometry}
          material={materials['Material.002']}
          position={[-4.337, -3.329, -6.525]}
          rotation={[-2.361, 1.015, -2.985]}
        />
        <mesh
          name="Torus006"
          castShadow
          receiveShadow
          geometry={nodes.Torus006.geometry}
          material={materials['Material.002']}
          position={[-5.328, -3.691, -5.959]}
          rotation={[-2.472, 0.99, 1.821]}
        />
        <mesh
          name="Torus007"
          castShadow
          receiveShadow
          geometry={nodes.Torus007.geometry}
          material={materials['Material.002']}
          position={[-6.203, -3.794, -5.173]}
          rotation={[3.136, 0.74, 0.774]}
        />
        <mesh
          name="Torus008"
          castShadow
          receiveShadow
          geometry={nodes.Torus008.geometry}
          material={materials['Material.002']}
          position={[-6.899, -3.623, -4.243]}
          rotation={[2.999, 0.696, -0.705]}
        />
        <mesh
          name="Torus009"
          castShadow
          receiveShadow
          geometry={nodes.Torus009.geometry}
          material={materials['Material.002']}
          position={[-7.371, -3.19, -3.248]}
          rotation={[2.643, 0.265, -2.108]}
        />
        <mesh
          name="Torus010"
          castShadow
          receiveShadow
          geometry={nodes.Torus010.geometry}
          material={materials['Material.002']}
          position={[-7.63, -2.56, -2.254]}
          rotation={[2.571, 0.239, 2.623]}
        />
        <mesh
          name="Torus011"
          castShadow
          receiveShadow
          geometry={nodes.Torus011.geometry}
          material={materials['Material.002']}
          position={[-7.716, -1.82, -1.295]}
          rotation={[2.462, 0.03, 1.067]}
        />
        <mesh
          name="Torus012"
          castShadow
          receiveShadow
          geometry={nodes.Torus012.geometry}
          material={materials['Material.002']}
          position={[-7.689, -1.08, -0.33]}
          rotation={[2.512, -0.016, -0.505]}
        />
        <mesh
          name="Torus013"
          castShadow
          receiveShadow
          geometry={nodes.Torus013.geometry}
          material={materials['Material.002']}
          position={[-7.524, -0.388, 0.649]}
          rotation={[2.481, -0.15, -2.076]}
        />
        <mesh
          name="Torus014"
          castShadow
          receiveShadow
          geometry={nodes.Torus014.geometry}
          material={materials['Material.002']}
          position={[-7.162, 0.211, 1.621]}
          rotation={[2.687, -0.299, 2.676]}
        />
        <mesh
          name="Torus015"
          castShadow
          receiveShadow
          geometry={nodes.Torus015.geometry}
          material={materials['Material.002']}
          position={[-6.51, 0.662, 2.485]}
          rotation={[2.529, -0.684, 1.034]}
        />
        <mesh
          name="Torus016"
          castShadow
          receiveShadow
          geometry={nodes.Torus016.geometry}
          material={materials['Material.002']}
          position={[-5.577, 0.972, 3.13]}
          rotation={[2.86, -0.893, -0.316]}
        />
        <mesh
          name="Torus017"
          castShadow
          receiveShadow
          geometry={nodes.Torus017.geometry}
          material={materials['Material.002']}
          position={[-4.468, 1.228, 3.51]}
          rotation={[2.411, -1.298, -2.291]}
        />
        <mesh
          name="Torus018"
          castShadow
          receiveShadow
          geometry={nodes.Torus018.geometry}
          material={materials['Material.002']}
          position={[-3.319, 1.557, 3.69]}
          rotation={[2.011, -1.206, 2.04]}
        />
        <mesh
          name="Torus019"
          castShadow
          receiveShadow
          geometry={nodes.Torus019.geometry}
          material={materials['Material.002']}
          position={[-2.174, 1.953, 3.797]}
          rotation={[1.76, -1.203, 0.229]}
        />
        <mesh
          name="Torus020"
          castShadow
          receiveShadow
          geometry={nodes.Torus020.geometry}
          material={materials['Material.002']}
          position={[-1.024, 2.295, 3.937]}
          rotation={[1.967, -1.325, -1.143]}
        />
        <mesh
          name="Torus021"
          castShadow
          receiveShadow
          geometry={nodes.Torus021.geometry}
          material={materials['Material.002']}
          position={[0.145, 2.472, 4.164]}
          rotation={[2.51, -1.277, -2.193]}
        />
        <mesh
          name="Torus022"
          castShadow
          receiveShadow
          geometry={nodes.Torus022.geometry}
          material={materials['Material.002']}
          position={[1.309, 2.451, 4.489]}
          rotation={[-2.791, -1.298, -2.812]}
        />
        <mesh
          name="Torus023"
          castShadow
          receiveShadow
          geometry={nodes.Torus023.geometry}
          material={materials['Material.002']}
          position={[2.424, 2.239, 4.903]}
          rotation={[-2.792, -1.157, 1.897]}
        />
        <mesh
          name="Torus024"
          castShadow
          receiveShadow
          geometry={nodes.Torus024.geometry}
          material={materials['Material.002']}
          position={[3.457, 1.859, 5.396]}
          rotation={[-2.339, -0.998, 0.732]}
        />
        <mesh
          name="Torus025"
          castShadow
          receiveShadow
          geometry={nodes.Torus025.geometry}
          material={materials['Material.002']}
          position={[4.335, 1.29, 5.972]}
          rotation={[-2.482, -0.805, -0.958]}
        />
        <mesh
          name="Torus026"
          castShadow
          receiveShadow
          geometry={nodes.Torus026.geometry}
          material={materials['Material.002']}
          position={[4.928, 0.512, 6.624]}
          rotation={[-2.118, -0.475, -2.294]}
        />
        <mesh
          name="Torus027"
          castShadow
          receiveShadow
          geometry={nodes.Torus027.geometry}
          material={materials['Material.002']}
          position={[5.097, -0.403, 7.277]}
          rotation={[-2.354, -0.114, 2.328]}
        />
        <mesh
          name="Torus028"
          castShadow
          receiveShadow
          geometry={nodes.Torus028.geometry}
          material={materials['Material.002']}
          position={[4.715, -1.316, 7.773]}
          rotation={[-1.835, 0.465, 0.689]}
        />
        <mesh
          name="Torus029"
          castShadow
          receiveShadow
          geometry={nodes.Torus029.geometry}
          material={materials['Material.002']}
          position={[3.888, -2.029, 7.987]}
          rotation={[-2.066, 0.899, -0.763]}
        />
        <mesh
          name="Torus030"
          castShadow
          receiveShadow
          geometry={nodes.Torus030.geometry}
          material={materials['Material.002']}
          position={[2.786, -2.468, 7.921]}
          rotation={[-1.086, 1.18, 3.101]}
        />
        <mesh
          name="Torus031"
          castShadow
          receiveShadow
          geometry={nodes.Torus031.geometry}
          material={materials['Material.002']}
          position={[1.616, -2.699, 7.725]}
          rotation={[-0.84, 1.373, 1.289]}
        />
        <mesh
          name="Torus032"
          castShadow
          receiveShadow
          geometry={nodes.Torus032.geometry}
          material={nodes.Torus032.material}
          position={[0.429, -2.785, 7.483]}
          rotation={[-0.291, 1.324, -0.817]}
        />
        <mesh
          name="Torus033"
          castShadow
          receiveShadow
          geometry={nodes.Torus033.geometry}
          material={materials['Material.002']}
          position={[-0.763, -2.759, 7.241]}
          rotation={[0.326, 1.382, -2.991]}
        />
        <mesh
          name="Torus034"
          castShadow
          receiveShadow
          geometry={nodes.Torus034.geometry}
          material={materials['Material.002']}
          position={[-1.954, -2.628, 7.037]}
          rotation={[0.45, 1.37, 1.6]}
        />
        <mesh
          name="Torus035"
          castShadow
          receiveShadow
          geometry={nodes.Torus035.geometry}
          material={materials['Material.002']}
          position={[-3.134, -2.387, 6.915]}
          rotation={[1.274, 1.296, -0.774]}
        />
        <mesh
          name="Torus036"
          castShadow
          receiveShadow
          geometry={nodes.Torus036.geometry}
          material={materials['Material.002']}
          position={[-4.275, -2.014, 6.943]}
          rotation={[1.689, 1.32, -2.75]}
        />
        <mesh
          name="Torus037"
          castShadow
          receiveShadow
          geometry={nodes.Torus037.geometry}
          material={nodes.Torus037.material}
          position={[-5.285, -1.485, 7.225]}
          rotation={[2.003, 0.875, 1.687]}
        />
        <mesh
          name="Torus038"
          castShadow
          receiveShadow
          geometry={nodes.Torus038.geometry}
          material={materials['Material.002']}
          position={[0.006, -0.746, -5.178]}
          rotation={[0.004, 0.03, 0.031]}
        />
        <mesh
          name="Cylinder002"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002.geometry}
          material={nodes.Cylinder002.material}
          position={[0, -0.739, -4.777]}
          scale={[0.187, 0.264, 0.187]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/vampire.glb')
