/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Arthor: Sabrina Medwinter
*/

import React, { useRef, useState, useEffect } from "react";
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three';
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {

  //  const [mixer] = useState(() => new THREE.AnimationMixer());
  const group = useRef();
  // const { nodes, materials, animations } = useGLTF("/park.glb");
    const { nodes, materials } = useGLTF("/park.glb");
  // const { actions } = useAnimations(animations, group);

// useFrame((state, delta) => mixer.update(delta));
//   useEffect(() => {
//     actions.current = { idle: mixer.clipAction(animations[0], group.current) };
//     actions.current.idle.play();
//     return () => animations.forEach((clip) => mixer.uncacheClip(clip));
//   }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[11.096, 0.159, -4.685]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={materials.plane}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_1.geometry}
          material={materials.ball}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass.geometry}
        material={materials.grass}
        position={[2.52, -0.366, -0.982]}
        scale={0.87}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GROUND.geometry}
        material={materials.ground}
        position={[5.597, 0.013, -4.222]}
        scale={[7.763, 10.966, 10.43]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pinktree1.geometry}
        material={materials.TREE}
        position={[0, -0.427, -2.14]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pinkleaves1.geometry}
          material={materials.LEAVES}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pinkleaves2.geometry}
          material={materials.LEAVES}
          position={[0.068, 0.059, -6.812]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pinktree2.geometry}
        material={materials.TREE}
        position={[0.07, -0.356, -8.959]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.greentree1.geometry}
        material={materials.TREE}
        position={[16.436, 0, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.leaves002.geometry}
          material={materials["LEAVES.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.leaves003.geometry}
          material={materials["LEAVES.001"]}
          position={[0, 0, -7.93]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.greentree1base.geometry}
        material={materials.TREE}
        position={[16.436, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shrub_1.geometry}
        material={materials["LEAVES.002"]}
        position={[0.159, -0.152, 1.098]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shrub_1001.geometry}
        material={materials["LEAVES.002"]}
        position={[-1.097, 0, 1.098]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shrub_1002.geometry}
        material={materials["LEAVES.002"]}
        position={[-1.097, 0, -9.841]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shrub_2.geometry}
        material={materials["LEAVES.002"]}
        position={[-0.401, 0, -12.224]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shrub_2001.geometry}
        material={materials["LEAVES.002"]}
        position={[15.208, -0.289, 0.319]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree004.geometry}
        material={materials.TREE}
        position={[16.436, 0, -7.93]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.petals.geometry}
        material={materials.LEAVES}
        position={[2.618, 2.565, -4.16]}
        scale={1.354}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.petals001.geometry}
        material={materials.LEAVES}
        position={[2.595, -5.774, -10.313]}
        scale={1.354}
      />
    </group>
  );
}

useGLTF.preload("/park.glb");

