/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Mikita_Hubanau (https://sketchfab.com/Mikita_Hubanau)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lost-robot-5a5c314a82864818a3fa5a0f71b17990
Title: Lost robot
*/

import React, { useRef, useState, useEffect } from "react";
import { useFrame } from '@react-three/fiber'
import { useGLTF, useAnimations } from "@react-three/drei";
import * as THREE from 'three';

export function Model(props) {

   const [mixer] = useState(() => new THREE.AnimationMixer());

  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/lost_robot.glb");
  const { actions } = useAnimations(animations, group);

useFrame((state, delta) => mixer.update(delta));
  useEffect(() => {
    actions.current = { idle: mixer.clipAction(animations[0], group.current) };
    actions.current.idle.play();
    return () => animations.forEach((clip) => mixer.uncacheClip(clip));
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="butterfly_6"
                position={[21.20465, 55.19244, 34.77749]}
                rotation={[0, -0.85302, 0]}
                scale={6.57354}
              >
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.butterfly}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <group name="butterfly__5" />
                </group>
              </group>
              <group
                name="Cube_7"
                position={[-0.48123, 59.97824, 0.69876]}
                scale={[-174.94368, 174.94368, 174.94368]}
              >
                <mesh
                  name="Object_14"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_14.geometry}
                  material={materials.Sphere}
                />
              </group>
              <group
                name="Light_8"
                position={[-76.03023, 179.40689, 51.88383]}
                rotation={[1.18995, 1.05514, -1.61147]}
                scale={0.38264}
              >
                <mesh
                  name="Object_16"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={materials["Material.002"]}
                />
              </group>
              <group
                name="Tree_main_9"
                position={[0, 38.15313, 0]}
                scale={0.41726}
              >
                <mesh
                  name="Object_18"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_18.geometry}
                  material={materials.Tree_main_and_grass_robot}
                />
              </group>
              <group
                name="Tree_up_10"
                position={[-5.91497, 116.30082, 4.80269]}
                scale={0.08195}
              >
                <mesh
                  name="Object_20"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_20.geometry}
                  material={materials.Tree_up}
                />
              </group>
              <group name="Robot_11" rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="Object_22"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_22.geometry}
                  material={materials.Robot}
                />
              </group>
              <group
                name="grass_main_12"
                position={[0, 38.96743, 0]}
                scale={0.10072}
              >
                <mesh
                  name="Object_24"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_24.geometry}
                  material={materials.Grass_down}
                />
              </group>
              <group
                name="Plane_13"
                position={[1.73929, 63.31559, -37.50671]}
                rotation={[0.00454, -0.00147, -0.00272]}
                scale={0.30501}
              >
                <mesh
                  name="Object_26"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_26.geometry}
                  material={materials["emission.001"]}
                />
              </group>
              <group
                name="Plane001_14"
                position={[57.85291, 33.04125, 73.42001]}
                scale={0.30617}
              >
                <mesh
                  name="Object_28"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_28.geometry}
                  material={materials["emission.001"]}
                />
              </group>
              <group
                name="Plane002_15"
                position={[69.08257, 33.24679, 19.36969]}
                rotation={[-0.01073, 0.00639, 0.00069]}
                scale={0.30753}
              >
                <mesh
                  name="Object_30"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_30.geometry}
                  material={materials["emission.001"]}
                />
              </group>
              <group
                name="Plane003_16"
                position={[92.86349, 32.31931, -15.17133]}
                scale={0.3063}
              >
                <mesh
                  name="Object_32"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_32.geometry}
                  material={materials["emission.001"]}
                />
              </group>
              <group
                name="Plane004_17"
                position={[30.67033, 65.46968, 56.26278]}
                scale={0.30548}
              >
                <mesh
                  name="Object_34"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_34.geometry}
                  material={materials["emission.001"]}
                />
              </group>
              <group
                name="Plane005_18"
                position={[82.24099, 58.9084, -33.30022]}
                rotation={[-0.00561, 0.00318, 0.00041]}
                scale={0.30579}
              >
                <mesh
                  name="Object_36"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_36.geometry}
                  material={materials["emission.001"]}
                />
              </group>
              <group
                name="Plane006_19"
                position={[44.66078, 70.54802, -12.69033]}
                rotation={[-0.00612, 0.00586, 0.00072]}
                scale={0.30475}
              >
                <mesh
                  name="Object_38"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_38.geometry}
                  material={materials["emission.001"]}
                />
              </group>
              <group
                name="Plane007_20"
                position={[47.79523, 53.9544, -14.12451]}
                rotation={[0.0046, -0.00271, -0.00341]}
                scale={0.30547}
              >
                <mesh
                  name="Object_40"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_40.geometry}
                  material={materials["emission.001"]}
                />
              </group>
              <group
                name="Plane008_21"
                position={[26.72578, 62.13906, 0.09394]}
                rotation={[0.00343, -0.00058, -0.00631]}
                scale={0.30667}
              >
                <mesh
                  name="Object_42"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_42.geometry}
                  material={materials["emission.001"]}
                />
              </group>
              <group
                name="Plane009_22"
                position={[36.19908, 51.66891, 4.71967]}
                rotation={[-0.00447, 0.00364, 0.00264]}
                scale={0.3059}
              >
                <mesh
                  name="Object_44"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_44.geometry}
                  material={materials["emission.001"]}
                />
              </group>
              <group
                name="Plane010_23"
                position={[26.15171, 58.31366, -24.4629]}
                rotation={[-0.0057, 0.00433, 0.00092]}
                scale={0.30556}
              >
                <mesh
                  name="Object_46"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_46.geometry}
                  material={materials["emission.001"]}
                />
              </group>
              <group
                name="Plane012_24"
                position={[-20.86481, 83.64501, -34.65026]}
                rotation={[-0.00757, 0.00434, 0.00103]}
                scale={0.30506}
              >
                <mesh
                  name="Object_48"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_48.geometry}
                  material={materials["emission.001"]}
                />
              </group>
              <group
                name="Plane013_25"
                position={[-37.30769, 67.81592, -4.28473]}
                rotation={[-0.00377, 0.00208, 0.0011]}
                scale={0.305}
              >
                <mesh
                  name="Object_50"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_50.geometry}
                  material={materials["emission.001"]}
                />
              </group>
              <group
                name="Plane014_26"
                position={[-46.17869, 50.70797, -23.87696]}
                rotation={[-0.00179, 0.00135, 0.00065]}
                scale={0.3049}
              >
                <mesh
                  name="Object_52"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_52.geometry}
                  material={materials["emission.001"]}
                />
              </group>
              <group
                name="Plane015_27"
                position={[-49.39355, 62.61076, -38.92332]}
                rotation={[0.00308, -0.00206, -0.00203]}
                scale={0.30539}
              >
                <mesh
                  name="Object_54"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_54.geometry}
                  material={materials["emission.001"]}
                />
              </group>
              <group
                name="Plane016_28"
                position={[-58.19683, 68.5246, -7.57183]}
                rotation={[0.00707, -0.00143, -0.00363]}
                scale={0.3052}
              >
                <mesh
                  name="Object_56"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_56.geometry}
                  material={materials["emission.001"]}
                />
              </group>
              <group
                name="Plane017_29"
                position={[-59.85276, 42.10645, -37.00456]}
                rotation={[-0.00449, 0.00346, 0.00106]}
                scale={0.30494}
              >
                <mesh
                  name="Object_58"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_58.geometry}
                  material={materials["emission.001"]}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/lost_robot.glb");
