'use client';
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF, PerspectiveCamera, Environment, OrbitControls } from '@react-three/drei';

export function Model(props) {
	const { nodes, materials } = useGLTF('/ball.glb');
	return (
		<group {...props} dispose={null}>
			<mesh castShadow receiveShadow geometry={nodes.disco.geometry} material={materials.metal} scale={2.5} />
			{/* <mesh
                castShadow
                receiveShadow
                geometry={nodes.Star.geometry}
                material={materials.green}
                position={[-2.874, 0.845, 0.032]}
                rotation={[0, 0.701, 0]}
                scale={[0.8, 0.8, 0.128]}
            /> */}
			{/* <mesh
                castShadow
                receiveShadow
                geometry={nodes.Star001.geometry}
                material={materials.blue}
                position={[2.735, -0.828, 0.032]}
                rotation={[0, 0.701, 0]}
                scale={[0.8, 0.8, 0.128]}
            /> */}
			<OrbitControls autoRotate maxDistance={6} minDistance={6} />
			<Environment files={'./ball.hdr'} intensity={1} blur={1} />
			<PerspectiveCamera
				makeDefault={false}
				far={100}
				near={0.1}
				fov={80}
				position={[6.051, 4.039, 5.413]}
				rotation={[-0.627, 0.71, 0.441]}
			/>
		</group>
	);
}

useGLTF.preload('/ball.glb');
