import Chess from "./images/3D/chess__alternate_view__by_kalecream.jpg";
import Park from "./images/3D/park_by_kalecream.jpg";
import UnderConstruction from "./images/Under_Construction_by_kalecream.webp";

const ThreeD = [Chess, Park, UnderConstruction];

export { ThreeD };

// interface GalleryData {
//   id: number;
//   src: StaticImageData | string;
//   name: string;
//   desc: string;
//   tags: string[];}

const GPhotos: GalleryData[] = [
  {
    year: "2023",
    month: "05",
    id: 0,
    src: "https://i.imgur.com/jCQIISQ.jpeg",
    name: "Punisher",
    desc: "A stray cat who occasionally visits me. She has a kitten and when she was named, I was unaware of her sex. Still, Punisher fits her.",
    tags: ["banana", "sunset"],
  },
  {
    id: 1,
    year: "2024",
    month: "06",
    src: "https://i.imgur.com/nD4m8JX.jpeg",
    name: "Chainsaw man!",
    desc: "Merch given by my brother and his partner.",
    tags: ["trees", "black and white"],
  },
  // {
  //   id: 2,
  //   year: "2023",
  //   month: "05",
  //   src: "https://imgur.com/Sd2DuQz.jpeg",
  //   name: "Wickie Wackie",
  //   desc: "Beach at sunrise",
  //   tags: ["earring", "jewelry"],
  // },
  {
    id: 4,
    year: "2023",
    month: "05",
    src: "https://i.imgur.com/p3ApPPh.jpeg",
    name: "West",
    desc: "A memory",
    tags: ["lunch", "food"],
  },
  // {
  //   id: 5,
  //   year: "2023",
  //   month: "05",
  //   src: "https://i.imgur.com/nIkVHY9.jpeg",
  //   name: "Flamingo",
  //   desc: "I went to the Zoo and finally got to see a Flamingo with my own two eyes.",
  //   tags: ["okra", "vegetable"],
  // },
  {
    id: 6,
    year: "2023",
    month: "05",
    src: "https://i.imgur.com/YvnWlaW.jpeg",
    name: "Wire-Wrapping",
    desc: "A pineapple on a table",
    tags: ["pineapple", "fruit"],
  },
  {
    id: 7,
    year: "2023",
    month: "11",
    src: "https://i.imgur.com/t5OmzeF.jpeg",
    name: "To A Free Palestine",
    desc: "The Palestine Rally last year",
    tags: ["pineapple", "fruit"],
  },
  {
    id: 8,
    year: "2023",
    month: "11",
    src: "https://i.imgur.com/Yr54suq.jpeg",
    name: "Window",
    desc: "Window at sunset",
    tags: ["pineapple", "fruit"],
  },
  {
    id: 9,
    year: "2023",
    month: "11",
    src: "https://i.imgur.com/QTA4SZw.jpeg",
    name: "Sorrel",
    desc: "Getting ready for Christmas!",
    tags: ["pineapple", "fruit"],
  },
  // {
  //   id: 10,
  //   year: "2024",
  //   month: "06",
  //   src: "https://i.imgur.com/Z4rJL6X.jpeg",
  //   name: "Sunset",
  //   desc: "A sunset over the ocean",
  //   tags: ["sunset", "ocean"],
  // },
  {
    id: 11,
    year: "2023",
    month: "05",
    src: "https://i.imgur.com/qBoPQhM.jpeg",
    name: "Seedlings",
    desc: "I don't remember what I was growing here xD",
    tags: ["seedling", "garden"],
  },
  // {
  //   id: 12,
  //   year: "2023",
  //   month: "05",
  //   src: "https://i.imgur.com/gvJo6sc.jpeg",
  //   name: "Mango Season",
  //   desc: "One of the best times of the year!",
  //   tags: ["seedling", "garden"],
  // },
  {
    id: 13,
    year: "2023",
    month: "05",
    src: "https://i.imgur.com/IBeDgxC.jpeg",
    name: "Sunbathing",
    desc: "Back when my Gerbera was still alive",
    tags: ["seedling", "garden"],
  },
  // {
  //   id: 14,
  //   year: "2023",
  //   month: "05",
  //   src: "https://i.imgur.com/12fyjHi.jpeg",
  //   name: "The Devil's Lettuce",
  //   desc: "The lettuce that caused a pandemic in my garden.",
  //   tags: ["seedling", "garden"],
  // },
  // {
  //   id: 15,
  //   year: "2023",
  //   month: "05",
  //   src: "https://i.imgur.com/XElNs2a.jpeg",
  //   name: "Kit",
  //   desc: "Unnamed Kitten from Punisher, last year",
  //   tags: ["seedling", "garden"],
  // },
  {
    id: 16,
    year: "2023",
    month: "06",
    src: "https://i.imgur.com/1iMVdlJ.jpeg",
    name: "Rose",
    desc: "From my parents' garden.",
    tags: ["seedling", "garden"],
  },
  {
    id: 17,
    year: "2023",
    month: "06",
    src: "https://i.imgur.com/8pt5sbK.jpeg",
    name: "Gloria's",
    desc: "Lunch by the seaside",
    tags: ["seedling", "garden"],
  },
  {
    id: 18,
    year: "2023",
    month: "06",
    src: "https://i.imgur.com/WKK4d1r.jpeg",
    name: "out",
    desc: "going out!",
    tags: ["seedling", "garden"],
  },
  {
    id: 19,
    year: "2024",
    month: "06",
    src: "https://i.imgur.com/zdeposJ.jpeg",
    name: "hollywell",
    desc: "I went to a rave then I went star-gazing/camping",
    tags: ["seedling", "garden"],
  },
  {
    id: 20,
    year: "2024",
    month: "06",
    src: "https://i.imgur.com/VopZGC7.jpeg",
    name: "Punisher",
    desc: "One more year pon the ______ dem!",
    tags: ["seedling", "garden"],
  },
  {
    id: 21,
    year: "2024",
    month: "06",
    src: "https://i.imgur.com/UzlzTYb.jpeg",
    name: "Camping",
    desc: "This was not my tent, but it had a nice view.",
    tags: ["seedling", "garden"],
  },
  {
    id: 22,
    year: "2024",
    month: "06",
    src: "https://i.imgur.com/46i0gO5.jpeg",
    name: "Hilly Flowers",
    desc: "I need to identify these.",
    tags: ["seedling", "garden"],
  },
  {
    id: 23,
    year: "2024",
    month: "06",
    src: "https://i.imgur.com/TdxK5VY.jpeg",
    name: "The Hills",
    desc: "I always appreciate staring at this",
    tags: ["seedling", "garden"],
  },
  {
    id: 24,
    year: "2023",
    month: "05",
    src: "https://i.imgur.com/8WhusAM.jpeg",
    name: "Joker",
    desc: "A card I found while walking",
    tags: ["seedling", "garden"],
  },
  {
    id: 25,
    year: "2024",
    month: "08",
    src: "https://i.imgur.com/kBE1hjB.jpeg",
    name: "Safety First",
    desc: "Masking while rock carving",
    tags: ["seedling", "garden"],
  },
  {
    id: 26,
    year: "2024",
    month: "08",
    src: "https://i.imgur.com/yWUBKT4.jpeg",
    name: "Rock Carving",
    desc: "The logo for a game I was working on",
    tags: ["seedling", "garden"],
  },
  {
    id: 27,
    year: "2024",
    month: "08",
    src: "https://i.imgur.com/aLfgecz.jpeg",
    name: "Escallion",
    desc: "I grew escallion around a dying plant to save space.",
    tags: ["seedling", "garden"],
  },
  // {
  //   id: 28,
  //   year: "2024",
  //   month: "06",
  //   src: "https://i.imgur.com/a0xm3RS.jpeg",
  //   name: "Joy",
  //   desc: "If I don't have silly what do I have?",
  //   tags: ["seedling", "garden"],
  // },
  // {
  //   id: 18,
  //   year: "2024",
  //   month: "08",
  //   src: "https://i.imgur.com/9QZ7U6s.jpeg",
  //   name: "Lunatic",
  //   desc: "My first and forever love.",
  //   tags: ["seedling", "garden"],
  // },
];

export { GPhotos };

import BiteSizedBingePoster from "./images/bitesizedbinge.webp";
import { GalleryData } from "@app/about/Gallery";

const OtherMultimediaProjectPictures = [BiteSizedBingePoster];

export { OtherMultimediaProjectPictures };
