name: Version Bump

on:
  push:
    branches:
      - master
jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Bump version and push changes
        run: |
          # Bump version using npm version patch (increment patch version)
          npm version minor

          # Push changes back to the repository
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Bump version"
          git push

        env:
          GITHUB_TOKEN: ${{ secrets.ACTION }}
